export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const TOPIC = "TOPIC";
export const TOPIC_SUCCESS = "TOPIC_SUCCESS";
export const TOPIC_FAILURE = "TOPIC_FAILURE";

export const BOARD = "BOARD";
export const BOARD_SUCCESS = "BOARD_SUCCESS";
export const BOARD_FAILURE = "BOARD_FAILURE";